### ISSUE TITLE
There should be no Wire.endTransmission after Wire.requestFrom

### ISSUE THREAD

**Issue by Koepel** [sparkfun/SparkFun_TMP102_Arduino_Library#2]
In the file SparkFunTMP102.cpp, in the function readRegister is a Wire.endTransmission after the Wire.requestFrom. That Wire.endTransmission can be removed, it is only used when writing data.

The Wire.requestFrom does a complete I2C transaction on its own. When Wire.requestFrom returns, the I2C transaction has completely finished and the received data is in a buffer in the Wire library.

**Comment by awende** [comment]
Fixed and pushed changes, thanks!
