### ISSUE TITLE
One-Shot/Conversion Ready (OS)

### ISSUE THREAD

**Issue by Levin-D** [sparkfun/SparkFun_TMP102_Arduino_Library#4]
Would it be possible to implement the one shot conversion in the library? Thanks a lot

**Comment by awende** [comment]
Added to [V1.1.0](https://github.com/sparkfun/SparkFun_TMP102_Arduino_Library/releases/tag/V1.1.0)

Reading the temperature seems to clear the sleep bit in the configuration register, but I added a second example to show how to use the one-shot function.
